# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html
from scrapy.item import Item, Field


class CrawlerTestItem(Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass

class XQCubeItem(Item):
#     以下在list中
    if_commit=Field()
    item_name=Field()
    table_name=Field()
    cube_id=Field()
    cube_symbol=Field()
    cube_name=Field()
    cube_description=Field()
    active_flag=Field()
    star=Field()
    market=Field()
    owner_id=Field()
    created_at=Field()
    updated_at=Field()
    last_rb_id=Field()
    daily_gain=Field()
    monthly_gain=Field()
    total_gain=Field()
    net_value=Field()
    rank_percent=Field()
    annualized_gain_rate=Field()
    bb_rate=Field()
    following=Field()
    follower_count=Field()
    view_rebalancing=Field()
    last_rebalancing=Field()
    last_success_rebalancing=Field()
    style_name=Field()
    style_degree=Field()
    tag=Field()
    lastcrawl=Field()
#     以下用在ret中
    date=Field()  
    value=Field() 
    percent=Field() 
#     以下用在rb中
    rb_id=Field()
    rb_status=Field()
    prev_rb_id=Field()
    rb_category=Field()
    exe_strategy=Field()
    rb_created_at=Field()
    rb_updated_at=Field()
    rb_cash=Field()
    rb_error_code=Field()
    rb_error_message=Field()
    rb_error_status=Field()
    rb_holdings=Field()
    rb_id2=Field()
    rb_stock_id=Field()
    rb_stock_name=Field()
    rb_stock_symbol=Field()
    rb_volume=Field()
    rb_price=Field()
    rb_net_value=Field()
    rb_weight=Field()
    rb_target_weight=Field()
    rb_prev_weight=Field()
    rb_prev_target_weight=Field()
    rb_prev_weight_adjusted=Field()
    rb_prev_volume=Field()
    rb_prev_price=Field()
    rb_prev_net_value=Field()
    rb_proactive=Field()

class XQCmtItem(Item):
    distance=Field()
    if_commit=Field()
    item_name=Field()
    stk_symbol=Field()
    fv_uid=Field()
    uid=Field()
    cmt_id=Field()
    uid=Field()
    cmt_title=Field()
    cmt_created_at=Field()
    retweet_count=Field()
    reply_count=Field()
    fv_count=Field()
    truncated=Field()
    commentId=Field()
    retweet_status_id=Field()
    cmt_symbol_id=Field()
    cmt_type=Field()
    cmt_edited_at=Field()
    retweeted_status=Field()
    fragment=Field()
    blocked=Field()
    blocking=Field()
    topic_symbol=Field()
    topic_title=Field()
    topic_desc=Field()
    donate_count=Field()
    donate_snowcoin=Field()
    cmt_view_count=Field()
    cmt_mark=Field()
    favorited=Field()
    favorited_created_at=Field()
    comment=Field()
    can_edit=Field()
    expend=Field()
    cmt_text=Field()
    cmt_source=Field()
    cmt_facets=Field()
    lastcrawl=Field()
    
class XQStkItem(Item): 
#     以下在stk_info中
    item_name=Field()
    stk_symbol=Field()
    stk_id=Field()
    stk_name=Field()
    stk_price=Field()
    lastcrawl=Field()
    
class XQGwsItem(Item):
#     以下是在info与ret表中的
    item_name=Field()
    gws_id=Field()
    gws_type=Field()
    gws_time=Field()
    gws_time_ms=Field()
    gws_symbol=Field()
    principal=Field()
    cash=Field()
    assets=Field()
    market_value=Field()
    monetary_unit=Field()
    shares=Field()
    hold_percent=Field()
    diluted_cost=Field()
    hold_cost=Field()
    accum_amount=Field()
    accum_rate=Field()
    float_amount=Field()
    float_rate=Field()
    day_amount=Field()
    day_rate=Field()
    week_amount=Field()
    week_rate=Field()
    month_amount=Field()
    month_rate=Field()
    quarter_amount=Field()
    quarter_rate=Field()
    year_amount=Field()
    year_rate=Field()
    uid=Field()
    group_id=Field()
    client_id=Field()
    created_at=Field()
    comment=Field()
    screen_name=Field()
    assets_desc=Field()
    update_time=Field()
    wk_flg=Field()
    value=Field()
    entry_date=Field()
#     以下是在rb表中的
    stk_symbol=Field()
    stk_name=Field()
    buy_sell=Field()
    rb_price=Field()
    rb_amount=Field()
    rb_time=Field()
    lastcrawl=Field()

class XQUserItem(Item):    
#     以下来自info表
    distance=Field()
    if_commit=Field()
    item_name=Field()
    subscribeable=Field()
    status=Field()
    common_count=Field()
    remark=Field()
    name=Field()
    location=Field()
    uid=Field()
    type=Field()
    url=Field()
    description=Field()
    domain=Field()
    blocking=Field()
    screen_name=Field()
    verified=Field()
    verified_type=Field()
    st_color=Field()
    allow_all_stock=Field()
    following=Field()
    donate_count=Field()
    verified_description=Field()
    status_count=Field()
    last_status_id=Field()
    follow_me=Field()
    friends_count=Field()
    city=Field()
    gender=Field()
    followers_count=Field()
    province=Field()
    recommend=Field()
    blog_description=Field()
    step=Field()
    intro=Field()
    stock_status_count=Field()
    stocks_count=Field()
    group_ids=Field()
    name_pinyin=Field()
    screenname_pinyin=Field()
    lastcrawl=Field()
#     以下来自stocks表
    stk_symbol=Field()
    comment=Field()
    sell_price=Field()
    buy_price=Field()
    create_at=Field()
    target_percent=Field()
    is_notice=Field()
    stk_name=Field()
    exchange=Field()
#     以下来自members/followers表
    mb_uid=Field()
    fl_uid=Field()
#     以下来自group表
    gid=Field()
    